reservationApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.calendar, name='calendar'),

    path('register/', views.registerUser, name='register'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('userProfile/<pk>/', views.userProfile, name='userProfile'),
    path('updateUser', views.updateUser, name='updateUser'),

    path('allAvailableBookingDates/', views.allAvailableBookingDates, name='allAvailableBookingDates'),
    path('allUnconfirmedReservations/', views.allUnconfirmedReservations, name='allUnconfirmedReservations'),
    path('allConfirmedReservations/', views.allConfirmedReservations, name='allConfirmedReservations'),
    path('allReservationsWithoutServiceProvider/', views.allReservationsWithoutServiceProvider, name='allReservationsWithoutServiceProvider'),

    path('filterServiceProviders/', views.filterServiceProviders, name='filterServiceProviders'),

    path('addEditAvailableBookingDate/', views.addEditAvailableBookingDate, name='addEditAvailableBookingDate'),
    path('deleteEvent/', views.deleteEvent, name='deleteEvent'),
    path('addEditReservation/', views.addEditReservation, name='addEditReservation'),
    path('confirmOrRejectReservation/', views.confirmOrRejectReservation, name='confirmOrRejectReservation'),
    path('dragEvent/', views.dragEvent, name='dragEvent'),

    path('deleteNotification/', views.deleteNotification, name='deleteNotification'),
    path('readNotification/', views.readNotification, name='readNotification'),

    path('eventTable/', views.eventTable, name='eventTable'),

    path('createStatistics/', views.createStatistics, name='createStatistics'),


    path('test/main/', views.PostListView.as_view(), name='main'),
    path('test/<pk>/', views.PostDetailView.as_view(), name='detail'),
    path('test/myTest', views.myTest, name='myTest')
]

reservationSystem/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from theme.views import change_theme
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('admin/', admin.site.urls),
    path('switch-theme/', change_theme, name="change-theme"), #switch_theme url musi być powyżej reservationApp.urls
    path('', include('reservationApp.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservationApp/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.db.models.signals import post_save
from django.core.exceptions import ValidationError
from icecream import ic
from datetime import timedelta
from django.utils import timezone


class AvailableBookingDate(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start = models.DateTimeField(null=True, blank=True)
    end = models.DateTimeField(null=True, blank=True)
    intervalTime = models.IntegerField(null=True, blank=True)
    breakBetweenIntervals = models.IntegerField(default=0)
    isDeleted = models.BooleanField(default=False)

    def __str__(self):
        if self.intervalTime:
            return f"Dostępny termin {self.user} od {self.start.strftime('%H:%M %d/%m/%Y')} do {self.end.strftime('%H:%M %d/%m/%Y')}. Czas wizyty = {self.intervalTime}"
        else:
            return f"Dostępny termin {self.user} od {self.start.strftime('%H:%M %d/%m/%Y')} do {self.end.strftime('%H:%M %d/%m/%Y')}"
    # def __str__(self):
    #     if self.intervalTime:
    #         return f"{self.user} {self.start.strftime('%H:%M %d/%m/%Y')} - {self.end.strftime('%H:%M %d/%m/%Y')} interval={self.intervalTime} break={self.breakBetweenIntervals}"
    #     else:
    #         return f"{self.user} {self.start.strftime('%H:%M %d/%m/%Y')} - {self.end.strftime('%H:%M %d/%m/%Y')}"

    def clean(self):
        if self.start and self.end and self.start >= self.end:
            raise ValidationError("Nie można zatwierdzić terminu. Koniec jest przed startem.", code="EndBeforeStart")
        if self.intervalTime and int(self.intervalTime) > 0:
            helpStartDate = self.start
            helpInterval = timedelta(minutes=int(self.intervalTime))
            helpBreakBetweenIntervals = timedelta(minutes=int(self.breakBetweenIntervals)) if self.breakBetweenIntervals else timedelta(minutes=0)
            condition = False
            while helpStartDate < self.end:
                helpStartDate += helpInterval + helpBreakBetweenIntervals
                if helpStartDate == self.end:
                    condition = True
            if not condition:
                raise ValidationError("Nie można zatwierdzić terminu. Start wraz z czasami pracy nie równa się Końcowi.", code="wrongIntervals")
        # Check consistency with related reservations
        if self.id:
            for reservation in self.reservation_set.filter(isAccepted=True, isDeleted=False):
                if self.intervalTime and int(self.intervalTime) > 0 and ((reservation.end - reservation.start) != timedelta(minutes=(int(self.intervalTime) + int(self.breakBetweenIntervals)))):
                    raise ValidationError(f"Dostepny termin posiada zatwierdzoną rezerwację z innym przedziałem czasowym.", code="durationMismatchWithReservation")
                # Check if the is reservation with bigger range
                if self.start > reservation.start or self.end < reservation.end:
                    raise ValidationError(f"Nie można zatwierdzić terminu. Dostepny termin posiada zatwierdzoną rezerwację z większym zakresem czasowym.", code="existReservationWithBiggerRange")
        # One user could have only one AvailableBookingDate in the same time
        if self.start and self.end and self.user:
            conflictDates = AvailableBookingDate.objects.filter(
                user=self.user,
                start__lt=self.end,
                end__gt=self.start,
                isDeleted=False
            ).exclude(id=self.id)
            if conflictDates.exists():
                raise ValidationError(f"Nie można zatwierdzić terminu. Użytkownik już ma spotkanie w tym czasie.", code="userAlreadyHaveExistingAvailableBookingDateInThisTime")

    def save(self, *args, **kwargs):
        fromUser = kwargs.pop('fromUser', None)
        self.clean()
        super().save(*args, **kwargs)
        for reservation in self.reservation_set.filter(isAccepted=False, isDeleted=False):
            if self.intervalTime and int(self.intervalTime) > 0:
                if (reservation.end - reservation.start) != timedelta(minutes=(int(self.intervalTime)) + int(self.breakBetweenIntervals)):
                    reservation.availableBookingDate = None
                    reservation.save()
                    Notification.createNotification(9, reservation.bookingPerson, fromUser, None, reservation)
            if reservation.end > self.end or reservation.start < self.start:
                reservation.availableBookingDate = None
                reservation.save()
                Notification.createNotification(9, reservation.bookingPerson, fromUser, None, reservation)

    # class Meta:
    #     verbose_name = "Dostępny termin"
    #     verbose_name_plural = "Dostępne terminy"


class Reservation(models.Model):
    id = models.AutoField(primary_key=True)
    bookingPerson = models.ForeignKey(User, on_delete=models.CASCADE)
    availableBookingDate = models.ForeignKey(AvailableBookingDate, on_delete=models.CASCADE, null=True, blank=True)
    start = models.DateTimeField(null=True, blank=True)
    end = models.DateTimeField(null=True, blank=True)
    isAccepted = models.BooleanField(default=False)
    isDeleted = models.BooleanField(default=False)

    def __str__(self):
        if self.isAccepted:
            return f"Potwierdzona rezerwacja {self.bookingPerson} od {self.start.strftime('%H:%M %d/%m/%Y')} do {self.end.strftime('%H:%M %d/%m/%Y')}"
        else:
            return f"Proponowana rezerwacja {self.bookingPerson} od {self.start.strftime('%H:%M %d/%m/%Y')} do {self.end.strftime('%H:%M %d/%m/%Y')}"

    def clean(self):
        if self.start and self.end and self.start >= self.end:
            raise ValidationError("Nie można zatwierdzić rezerwacji. Data końcowa nie może być przed początkową.")
        conflictingAcceptedReservations = Reservation.objects.filter(
            # availableBookingDate=self.availableBookingDate,
            bookingPerson=self.bookingPerson,
            isAccepted=True,
            start__lt=self.end,
            end__gt=self.start,
            isDeleted=False
        ).exclude(pk=self.pk)  # Exclude self if instance is being updated
        if conflictingAcceptedReservations.exists():
            raise ValidationError("Nie można zatwierdzić rezerwacji. Następuje kolizja terminów. Użytkownik już ma zaakceptowaną rezerwacje w tym terminie", code="conflict")
        if self.isAccepted:
            conflictingNotAcceptedReservations = Reservation.objects.filter(
                bookingPerson=self.bookingPerson,
                isAccepted=False,
                start__lt=self.end,
                end__gt=self.start,
                isDeleted=False
            ).exclude(pk=self.pk)
            for conflictNotAcceptedReservation in conflictingNotAcceptedReservations:
                conflictNotAcceptedReservation.isDeleted = True
                conflictNotAcceptedReservation.save()
        if self.availableBookingDate:
            # Check for mismatch between interval+break and duration time
            if self.availableBookingDate.intervalTime and int(self.availableBookingDate.intervalTime) > 0:
                if self.end - self.start != timedelta(minutes=(int(self.availableBookingDate.intervalTime) + int(self.availableBookingDate.breakBetweenIntervals))):
                    raise ValidationError("Nie można zatwierdzić rezerwacji. Czas rezerwacji nie pokrywa się z przedziałem czasowym dostępnego terminu.", code="durationMismatch")
            # Check if reservation time is in available bookind date range time
            if self.availableBookingDate.end < self.end or self.start < self.availableBookingDate.start:
                raise ValidationError("Nie można zatwierdzić rezerwacji. Zakres rezerwacji przekracza zakres dostępnego terminu.", code="reservationExceedRange")
            # One user could have only one Reservation in the same time
            if self.start and self.end and self.bookingPerson:
                conflictDates = Reservation.objects.filter(
                    bookingPerson=self.bookingPerson,
                    availableBookingDate=self.availableBookingDate,
                    start__lt=self.end,
                    end__gt=self.start,
                    isDeleted=False
                ).exclude(id=self.id)
                if conflictDates.exists():
                    raise ValidationError(f"Nie można dodac rezerwacji. Użytkownik już ma rezerwacje w tym czasie w tym dostepnym terminie.", code="userAlreadyHaveExistingReservationInThisAvailableBookingDateInThisTime")

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    age = models.IntegerField(null=True, blank=True)
    UNDEFINED = 'UNDEFINED'
    MALE = 'MALE'
    FEMALE = 'FEMALE'
    SEX_CHOICES = [
        (UNDEFINED, 'Brak'),
        (MALE, 'Mężczyzna'),
        (FEMALE, 'Kobieta'),
    ]
    sex = models.CharField(max_length=30, choices=SEX_CHOICES, null=True, blank=True)
    description = models.CharField(max_length=300, null=True, blank=True)
    profileImage = models.ImageField(default='default.jpg', upload_to='profilePictures')
    #userColor = models.CharField(max_length=20, default="white")

    def __str__(self):
        return f"{self.user.username} {self.user.first_name} {self.user.last_name} {self.age} {self.sex}"

    def save(self):
        super().save()
        img = Image.open(self.profileImage.path)
        img = img.resize((300, 300))
        img.save(self.profileImage.path)


def create_profile(sender, instance, created, **kwargs):
    if created:
        newUserProfile = UserProfile(user=instance)
        newUserProfile.save()


post_save.connect(create_profile, sender=User)


class Notification(models.Model):

reservationApp/templates/accounts/login.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block content %}
    <head>
        <title>Login</title>
    </head>
    <body>
        <div class="flex justify-center items-center">
        {% with customClass="flex-auto border border-solid border-gray-300 bg-gray-50 text-gray-900 sm:text-2xl rounded-r focus:ring-primary-600 focus:border-primary-600 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-gray-50 dark:focus:ring-blue-500 dark:focus:border-blue-500 form-control" %}
            <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
                <a href="#" class="flex items-center mb-2 text-2xl font-bold text-gray-900 dark:text-gray-50">
                    <i class="fa-solid fa-house w-8 h-8 mr-2"></i>
                    System rezerwacji terminów
                </a>
                <div class="w-full bg-gray-50 rounded-lg shadow border-2 dark:border-2 md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
                    <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                        <h1 class="text-2xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-gray-50 text-center">
                            Zaloguj się
                        </h1>
                        <form method="POST" action="" class="space-y-4 md:space-y-6">
                            {% csrf_token %}
                            <div class="relative flex items-stretch">
                                <div class="flex items-center whitespace-nowrap rounded-l border border-solid border-gray-300 bg-gray-50 dark:bg-gray-700 dark:text-gray-50 dark:border-gray-600 px-4">
                                    <i class="fas fa-user text-xl"></i>
                                </div>
                                {{ form.username|add_class:customClass }}
                            </div>
                            <div class="relative flex items-stretch">
                                <div class="flex items-center whitespace-nowrap rounded-l border border-solid border-gray-300 bg-gray-50 dark:bg-gray-700 dark:text-gray-50 dark:border-gray-600 px-4">
                                    <i class="fas fa-key text-xl"></i>
                                </div>
                                {{ form.password|add_class:customClass }}
                            </div>
                            <div class="form-text text-red-600 dark:text-red-500 small">
                                {{ form.password.errors }}
                                {% for error in errors %}
                                    {% if error == 'Username or password is incorrect' %}
                                        <p>Nazwa użytkownika lub hasło jest nieprawidłowe.</p>
                                    {% else %}
                                        <p>{{ error }}</p>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            {% if request.GET.next %}
                                <input type="hidden" name="next" value="{{request.GET.next}}" />
                            {% endif %}
                            <div class="login_container">
                                <input type="submit" value="zaloguj się" class="w-full text-gray-50 bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-bold rounded-lg text-3xl px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
                            </div>
                            <p class="text-xl font-light text-gray-500 dark:text-gray-400">
                              Nie masz konta? <a href="{% url 'register' %}" class="font-medium text-primary-600 hover:underline dark:text-primary-500">Zarejestruj się</a>
                            </p>
                        </form>
                    </div>
                </div>
            </div>
        {% endwith %}
        </div>
    </body>
{% endblock %}

reservationApp/templates/accounts/register.html
{% extends 'base.html' %}
{% load custom_filters %}


{% block content %}
    <head>
        <title>Register</title>
    </head>
    {% with customClass="flex-auto border border-solid border-gray-300 bg-gray-50 text-gray-900 sm:text-2xl rounded-r focus:ring-primary-600 focus:border-primary-600 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-gray-50 dark:focus:ring-blue-500 dark:focus:border-blue-500 form-control" %}
    <body>
        <div>
            <section id="registerContainer" class="flex justify-center items-center mt-20" style="height: calc(100vh - 8rem)">
                <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto lg:py-0">
                    <a href="" class="flex items-center mb-2 text-2xl font-bold text-gray-900 dark:text-gray-50">
                        <i class="fa-solid fa-house w-8 h-8 mr-2"></i>
                        System rezerwacji terminów
                    </a>
                    <div class="w-full bg-gray-50 rounded-lg shadow border-2 dark:border-2 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
                        <div class="px-12 py-6 space-y-4 md:space-y-4 sm:px-8 sm:py-4">
                            <h1 class="text-2xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-gray-50 text-center">
                                Zarejestruj konto
                            </h1>
                            <form class="space-y-4 md:space-y-4" method="POST" action="">
                                {% csrf_token %}
                                <div class="relative flex items-stretch">
                                    <div class="flex items-center whitespace-nowrap rounded-l border border-solid border-gray-300 bg-gray-50 dark:bg-gray-700 dark:text-gray-50 dark:border-gray-600 px-4">
                                        <i class="fa-solid fa-id-card text-xl"></i>
                                    </div>
                                    {{ form.username|add_class:customClass }}
                                </div>
                                <div class="form-text text-red-600 dark:text-red-500 small">{{ form.username.errors }}</div>
                                <div class="relative flex items-stretch">
                                    <div class="flex items-center whitespace-nowrap rounded-l border border-solid border-gray-300 bg-gray-50 dark:bg-gray-700 dark:text-gray-50 dark:border-gray-600 px-4">
                                        <i class="fas fa-user text-xl"></i>
                                    </div>
                                    {{ form.first_name|add_class:customClass }}
                                </div>
                                <div class="relative flex items-stretch">
                                    <div class="flex items-center whitespace-nowrap rounded-l border border-solid border-gray-300 bg-gray-50 dark:bg-gray-700 dark:text-gray-50 dark:border-gray-600 px-4">
                                        <i class="fas fa-user text-xl"></i>
                                    </div>
                                    {{ form.last_name|add_class:customClass }}
                                </div>
                                <div class="relative flex items-stretch">
                                    <div class="flex items-center whitespace-nowrap rounded-l border border-solid border-gray-300 bg-gray-50 dark:bg-gray-700 dark:text-gray-50 dark:border-gray-600 px-4">
                                        <i class="fas fa-envelope-square text-xl"></i>
                                    </div>
                                    {{ form.email|add_class:customClass }}
                                </div>
                                <div class="form-text text-red-600 dark:text-red-500 small">{{ form.email.errors }}</div>
                                <div class="relative flex items-stretch">
                                    <div class="flex items-center whitespace-nowrap rounded-l border border-solid border-gray-300 bg-gray-50 dark:bg-gray-700 dark:text-gray-50 dark:border-gray-600 px-4">
                                        <i class="fas fa-key text-xl"></i>
                                    </div>
                                    {{ form.password1|add_class:customClass }}
                                </div>
                                <div class="relative flex items-stretch">
                                    <div class="flex items-center whitespace-nowrap rounded-l border border-solid border-gray-300 bg-gray-50 dark:bg-gray-700 dark:text-gray-50 dark:border-gray-600 px-4">
                                        <i class="fas fa-key text-xl"></i>
                                    </div>
                                    {{ form.password2|add_class:customClass }}
                                </div>
                                <div class="form-text text-red-600 dark:text-red-500 small">
                                    {% for error in form.password2.errors %}
                                        {% if error == "The two password fields didn’t match." %}
                                            <p>Podane hasła nie są identyczne.</p>
                                        {% elif error == "The password is too similar to the username." %}
                                            <p>Podane hasła jest zbyt podobne do nazwy użytkownika.</p>
                                        {% elif error == "This password is too short. It must contain at least 8 characters." %}
                                            <p>Podane hasło jest zbyt krótkie. Hasło musi mieć przynajmniej 8 znaków.</p>
                                        {% elif error == "This password is too common." %}
                                            <p>Podane hasło jest zbyt powszechne.</p>
                                        {% else %}
                                            <p>{{ form.password2.errors }}</p>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                                <button type="submit" class="w-full text-gray-50 bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-bold rounded-lg text-3xl px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
                                    Zarejestruj się
                                </button>
                                <p class="text-xl font-light text-gray-500 dark:text-gray-400">
                                  Masz konto? <a href="{% url 'login' %}" class="font-medium text-primary-600 hover:underline dark:text-primary-500">Zaloguj się</a>
                                </p>
                            </form>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </body>
    {% endwith %}
{% endblock %}

reservationApp/templates/accounts/userProfile.html
{% extends 'base.html' %}

{% block content %}
    <head>
        <title>Profil uźytkownika</title>
    </head>
        <body>
            <div class="container mx-auto mt-8">
            <div class="grid grid-cols-1 md:grid-cols-3">
                <div class="md:col-span-1">
                    <div class="w-300 h-300 overflow-hidden rounded-lg shadow-md">
                        <img src="{{ userProfile.profileImage.url }}" alt="Profile Image" class="w-full h-full object-cover">
                    </div>
                </div>
                <div class="md:col-span-2 h-full">
                    <div class="h-full bg-gray-50 dark:bg-gray-700 text-gray-950 dark:text-gray-50 p-6 rounded-lg shadow-md">
    {#                    <h2 class="text-5xl font-bold mb-4">Uzytkownik: {{ userProfile.user.username }}</h2>#}
                        <p class="text-3xl mb-2"><strong>Imie:</strong> {{ userProfile.user.first_name }}</p>
                        <p class="text-3xl mb-2"><strong>Nazwisko:</strong> {{ userProfile.user.last_name }}</p>
                        <p class="text-3xl mb-2"><strong>Email:</strong> {{ userProfile.user.email }}</p>
                        <p class="text-3xl mb-2"><strong>Wiek:</strong> {% if userProfile.age is not None %} {{ userProfile.age }} {% endif %}</p>
                        <p class="text-3xl mb-2"><strong>Płeć:</strong> {{ userProfile.get_sex_display }}</p>
                        <div>
                            <div class="grid grid-cols-12 gap-4">
                                <div class="col-span-9">
                                    <p class="text-3xl"><strong>Opis:</strong></p>
                                    <p>{% if userProfile.description is not None %} {{ userProfile.description }} {% endif %}</p>
                                </div>
                                <div class="col-span-3 flex items-end justify-end">
                                    {% if request.user.id == userProfile.user.id %}
                                        <a href="{% url 'updateUser' %}" class="py-1 px-3 text-2xl font-semibold text-gray-900 focus:outline-none bg-gray-50 rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">Edytuj dane</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
{% endblock %}